### ISSUE TITLE
JSON Decode Error in geo_search

### ISSUE THREAD

**Issue by bbuzz31** [asfadmin/Discovery-asf_search#83]
Hi all, I'm getting a JSON decode error (see below) when trying to use `asf_search.geo_search()`.

Here's a formerly working MWE:
```
import asf_search as asf
dct_kw = {'platform': 'Sentinel-1', 'processingLevel': 'SLC', 'relativeOrbit': [4], 'frame': None, 'start': None, 'end': None, 'lookDirection': None, 'intersectsWith': None}
asf.geo_search(**dct_kw)
```

Tested on Linux and MacOS, with current asf_search conda version v3.0.6.
I've also tested with my previous version, but this also fails, suggesting something changed upstream of the asf_search routines.
(P.S. I'm not sure what asf_search version I had previously working, as `asf.__version__` returns 0.0.0. 

Thanks in advance.

`
Traceback (most recent call last):
  File "/home/buzzanga/BB_LIB/bin/ASF_DL-search.py", line 238, in <module>
    Downloader(inps)()
  File "/home/buzzanga/BB_LIB/bin/ASF_DL-search.py", line 161, in __call__
    scenes   = self.query_asf()
  File "/home/buzzanga/BB_LIB/bin/ASF_DL-search.py", line 232, in query_asf
    scenes = asf.geo_search(**dct_kw)
  File "/u/leffe-data2/buzzanga/Miniconda3/envs/FRInGE/lib/python3.9/site-packages/asf_search/search/geo_search.py", line 61, in geo_search
    return search(**data)
  File "/u/leffe-data2/buzzanga/Miniconda3/envs/FRInGE/lib/python3.9/site-packages/asf_search/search/search.py", line 147, in search
    raise ASFSearch5xxError(f'HTTP {response.status_code}: {response.json()["error"]["report"]}')
  File "/u/leffe-data2/buzzanga/Miniconda3/envs/FRInGE/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/u/leffe-data2/buzzanga/Miniconda3/envs/FRInGE/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/u/leffe-data2/buzzanga/Miniconda3/envs/FRInGE/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/u/leffe-data2/buzzanga/Miniconda3/envs/FRInGE/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by bbuzz31** [comment]
This issue seems to be resolved!

**Comment by nabolfat** [comment]
I am getting the same issue but I was not successful in resolving it.

**Comment by bbuzz31** [comment]
I'm getting a similar error now with the same command (traceback below).
Any thoughts?

```---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File ~/Miniconda3/envs/ARIA/lib/python3.10/site-packages/requests/models.py:910, in Response.json(self, **kwargs)
    909 try:
--> 910     return complexjson.loads(self.text, **kwargs)
    911 except JSONDecodeError as e:
    912     # Catch JSON-related errors and raise as requests.JSONDecodeError
    913     # This aliases json.JSONDecodeError and simplejson.JSONDecodeError

File ~/Miniconda3/envs/ARIA/lib/python3.10/json/__init__.py:346, in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    343 if (cls is None and object_hook is None and
    344         parse_int is None and parse_float is None and
    345         parse_constant is None and object_pairs_hook is None and not kw):
--> 346     return _default_decoder.decode(s)
    347 if cls is None:

File ~/Miniconda3/envs/ARIA/lib/python3.10/json/decoder.py:337, in JSONDecoder.decode(self, s, _w)
    333 """Return the Python representation of ``s`` (a ``str`` instance
    334 containing a JSON document).
    335
    336 """
--> 337 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338 end = _w(s, end).end()

File ~/Miniconda3/envs/ARIA/lib/python3.10/json/decoder.py:355, in JSONDecoder.raw_decode(self, s, idx)
    354 except StopIteration as err:
--> 355     raise JSONDecodeError("Expecting value", s, err.value) from None
    356 return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 asf.geo_search(**dct_kw)

File ~/Miniconda3/envs/ARIA/lib/python3.10/site-packages/asf_search/search/geo_search.py:62, in geo_search(absoluteOrbit, asfFrame, beamMode, collectionName, campaign, end, flightDirection, frame, instrument, intersectsWith, lookDirection, platform, polarization, processingDate, processingLevel, relativeOrbit, start, maxResults, host, cmr_token, cmr_provider)
     59 kwargs = locals()
     60 data = dict((k,v) for k,v in kwargs.items() if v is not None and v != '')
---> 62 return search(**data)

File ~/Miniconda3/envs/ARIA/lib/python3.10/site-packages/asf_search/search/search.py:169, in search(absoluteOrbit, asfFrame, beamMode, collectionName, campaign, maxDoppler, minDoppler, end, maxFaradayRotation, minFaradayRotation, flightDirection, flightLine, frame, granule_list, groupID, insarStackId, instrument, intersectsWith, lookDirection, offNadirAngle, platform, polarization, processingDate, processingLevel, product_list, relativeOrbit, season, start, maxResults, host, cmr_token, cmr_provider)
    167         raise ASFSearch4xxError(f'HTTP {response.status_code}: {response.json()["error"]["report"]}')
    168     if 500 <= response.status_code <= 599:
--> 169         raise ASFSearch5xxError(f'HTTP {response.status_code}: {response.json()["error"]["report"]}')
    170     raise ASFServerError(f'HTTP {response.status_code}: {response.json()["error"]["report"]}')
    172 products = [ASFProduct(f) for f in response.json()['features']]

File ~/Miniconda3/envs/ARIA/lib/python3.10/site-packages/requests/models.py:917, in Response.json(self, **kwargs)
    915     raise RequestsJSONDecodeError(e.message)
    916 else:
--> 917     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)

JSONDecodeError: [Errno Expecting value] <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
: 0
```
Looks to be triggered here:
```
> ../lib/python3.10/site-packages/requests/models.py(917)json()
    915                 raise RequestsJSONDecodeError(e.message)
    916             else:
--> 917                 raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    918
    919     @property
