### ISSUE TITLE
[Bug] No module named 'asf_search.CMR' after recent version to 3.1.0

### ISSUE THREAD

**Issue by brentwilder** [asfadmin/Discovery-asf_search#86]
**Describe the bug**
After the recent update to version 3.1.0, I couldn't import asf. When importing I get the following error message (see attached). [bug3.1.0.txt](https://github.com/asfadmin/Discovery-asf_search/files/8527829/bug3.1.0.txt) . It was working however with version 3.0.0.

**To Reproduce**
1. import `asf_search as asf`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Comment by asjohnston-asf** [comment]
+1, seeing the same after installing v3.1.0 from PyPI:
```
$ python -m pip install asf_search==3.1.0
Collecting asf_search==3.1.0
  Downloading asf_search-3.1.0-py3-none-any.whl (22 kB)
Collecting requests
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting importlib-metadata
  Using cached importlib_metadata-4.11.3-py3-none-any.whl (18 kB)
Collecting pytz
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting shapely
  Downloading Shapely-1.8.1.post1-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 8.0 MB/s eta 0:00:00
Collecting zipp>=0.5
  Using cached zipp-3.8.0-py3-none-any.whl (5.4 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Installing collected packages: pytz, certifi, zipp, urllib3, six, shapely, idna, charset-normalizer, requests, python-dateutil, importlib-metadata, asf_search
Successfully installed asf_search-3.1.0 certifi-2021.10.8 charset-normalizer-2.0.12 idna-3.3 importlib-metadata-4.11.3 python-dateutil-2.8.2 pytz-2022.1 requests-2.27.1 shapely-1.8.1.post1 six-1.16.0 urllib3-1.26.9 zipp-3.8.0
(asf_search) asjohnston@xps:~$ python
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:39:04) [GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asf_search
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages/asf_search/__init__.py", line 20, in <module>
    from .search import *
  File "/home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages/asf_search/search/__init__.py", line 6, in <module>
    from .campaigns import campaigns
  File "/home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages/asf_search/search/campaigns.py", line 2, in <module>
    from asf_search.CMR.MissionList import get_campaigns
ModuleNotFoundError: No module named 'asf_search.CMR'
```

**Comment by SpicyGarlicAlbacoreRoll** [comment]
@brentwilder V3.1.1 should now be available with the fix, Thank you for reporting this!

**Comment by asjohnston-asf** [comment]
Resolved for me! Thank you!
```
$ python -m pip install asf_search==3.1.1
Collecting asf_search==3.1.1
  Downloading asf_search-3.1.1-py3-none-any.whl (23 kB)
Requirement already satisfied: requests in /home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages (from asf_search==3.1.1) (2.27.1)
Requirement already satisfied: python-dateutil in /home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages (from asf_search==3.1.1) (2.8.2)
Requirement already satisfied: pytz in /home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages (from asf_search==3.1.1) (2022.1)
Requirement already satisfied: importlib-metadata in /home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages (from asf_search==3.1.1) (4.11.3)
Requirement already satisfied: shapely in /home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages (from asf_search==3.1.1) (1.8.1.post1)
Requirement already satisfied: zipp>=0.5 in /home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages (from importlib-metadata->asf_search==3.1.1) (3.8.0)
Requirement already satisfied: six>=1.5 in /home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages (from python-dateutil->asf_search==3.1.1) (1.16.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages (from requests->asf_search==3.1.1) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages (from requests->asf_search==3.1.1) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages (from requests->asf_search==3.1.1) (1.26.9)
Requirement already satisfied: certifi>=2017.4.17 in /home/asjohnston/miniconda3/envs/asf_search/lib/python3.10/site-packages (from requests->asf_search==3.1.1) (2021.10.8)
Installing collected packages: asf_search
  Attempting uninstall: asf_search
    Found existing installation: asf-search 3.1.0
    Uninstalling asf-search-3.1.0:
      Successfully uninstalled asf-search-3.1.0
Successfully installed asf_search-3.1.1
(asf_search) asjohnston@xps:~/scratches$ python
Python 3.10.4 | packaged by conda-forge | (main, Mar 24 2022, 17:39:04) [GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asf_search
>>> 
```
